### ISSUE TITLE
HyperTransformer: Avoid re-ordering columns if possible

### ISSUE THREAD

**Issue by csala** [sdv-dev/RDT#151]
* Reversible Data Transforms version: v0.3.0

### Description

When transforming data, the HyperTransformer always pops the column out of the input dataframe before transforming and assigning the output of the transformation back into the dataframe, which appends the transformed columns at the end of it.

If the output of the transformation is more than one column an alteration of the column is not avoidable. However, when the output is just one column, and when there are columns that are not being transformed, this ends up in a reordering of the columns that could have been avoided. 

This should be taken into account by trying to respect the order of the columns when possible.

### How to reproduce

To reproduce the problem two things are required:

1. The `transform` method must be called with additional columns that will not be transformed.
2. The transformers used should not create any additional columns (like the `CategoricalTransformer`).

The result will be a DataFrame with the same columns as the input but with a different order.

```
In [1]: import pandas as pd

In [2]: import rdt

In [3]: data = pd.DataFrame({
   ...:     'category': ['a', 'b', 'c'],
   ...:     'float': [1., 2., 3.],
   ...: })

In [4]: ht = rdt.HyperTransformer()

In [5]: ht.fit(data[['category']])

In [6]: ht.transform(data)
Out[6]: 
   float  category
0    1.0  0.833333
1    2.0  0.500000
2    3.0  0.166667
```

**Comment by npatki** [comment]
Fixed by #405
