### ISSUE TITLE
Add RDT API Reference to SDV Documentation

### ISSUE THREAD

**Issue by csala** [sdv-dev/RDT#159]
Just that. The Transformers could be exposed as a sub-section within the API reference of SDV.

**Comment by npatki** [comment]
The [RDT documentation](https://docs.sdv.dev/rdt) is available as a standalone website. Additionally the new [SDV 1.0 docs](https://docs.sdv.dev/sdv) contain references to the relevant section of RDTs. Eg.
- [Viewing transformers](https://docs.sdv.dev/sdv/single-table-data/modeling/advanced-features/transform-and-anonymize#viewing-the-transformations)
- [Modifying transformers](https://docs.sdv.dev/sdv/single-table-data/modeling/advanced-features/transform-and-anonymize#modifying-the-transformers)
- [Anonymizing data](https://docs.sdv.dev/sdv/single-table-data/modeling/advanced-features/transform-and-anonymize#anonymizing-sensitive-data)
