### ISSUE TITLE
Audit BooleanTransformer

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/RDT#179]
Audit the time and memory performance of `transformers.BooleanTransformer` https://github.com/sdv-dev/RDT/blob/cf62cc33c732f0bdec2aef9a88111fca11ae1be4/rdt/transformers/boolean.py#L10

**Comment by katxiao** [comment]
For `fit`, the bulk of the time (~97%) is going into the call to `NullTransformer`, which we will optimize in a separate issue.
https://github.com/sdv-dev/RDT/blob/cf62cc33c732f0bdec2aef9a88111fca11ae1be4/rdt/transformers/boolean.py#L46

In the `transform` step, 99% of the time is spent in this dropping null values and casting into ints -  https://github.com/sdv-dev/RDT/blob/cf62cc33c732f0bdec2aef9a88111fca11ae1be4/rdt/transformers/boolean.py#L65

In the `reverse_tranform` step, 88% of the time is spent in this dropping null values and casting into bools -  https://github.com/sdv-dev/RDT/blob/cf62cc33c732f0bdec2aef9a88111fca11ae1be4/rdt/transformers/boolean.py#L88

For both `transform` and `reverse_transform`, the casting and rounding only contributes ~3%, and most of the work is done when dropping null values.

**Comment by katxiao** [comment]
Potential improvements:

For `transform`, we could change 
`data.loc[data.notnull() = data.dropna().astype(int)` 
to 
`data = data = pd.to_numeric(data, errors='coerce')` 
in order to avoid dropping the null values. The `to_numeric` function will convert any `None` values to `Nan`. The main difference is that `data` will be a `float64` series instead of an `int` series when being passed into the `NullTransformer`. The `transform` output seems to be unaffected by this change.

Original method:
```
CPU times: user 1.99 ms, sys: 0 ns, total: 1.99 ms
Wall time: 2.01 ms
```
Conversion takes `99%` of the method runtime.

Updated method:
```
CPU times: user 443 µs, sys: 0 ns, total: 443 µs
Wall time: 451 µs
```
Conversion takes `91%` of the method runtime.

**Comment by katxiao** [comment]
Potential improvements to `reverse_transform`:

Instead of using `pd.notnull(data)`, we could make use of pandas built in support for Nullable [boolean](https://pandas.pydata.org/pandas-docs/version/1.0/user_guide/boolean.html) data types by changing 
`data[pd.notnull(data)] = np.round(data[pd.notnull(data)]).astype(bool)`
to
`np.round(data).astype('boolean')`

This improves the runtime from
```
CPU times: user 7.38 ms, sys: 12 µs, total: 7.4 ms
Wall time: 11 ms
```
~91% of the function runtime
to
```
CPU times: user 2.5 ms, sys: 51 µs, total: 2.56 ms
Wall time: 2.69 ms
```
~80% of the function runtime

Pandas also has an experimental [Int64](https://pandas.pydata.org/pandas-docs/version/1.0/user_guide/integer_na.html) Nullable datatype, but not sure we want to use it for `transform` since it could change at anytime.

**Comment by csala** [comment]
Excellent findings @katxiao !

I think both proposals are good (and I agree, I would not try the nullable Int64 yet, the float is fine, here)!
