### ISSUE TITLE
Audit the `NumericalTransformer`

### ISSUE THREAD

**Issue by fealho** [sdv-dev/RDT#181]
Audit for the time/memory performance of the `NumericalTransformer`.

In the `fit` stage, besides fitting the `NullTransformer`, the most time is consumed by:
https://github.com/sdv-dev/RDT/blob/05b4036bddca04ab76967dc9d2de39317d2d7ab1/rdt/transformers/numerical.py#L105

In the `transform` stage, most of the time is consumed by:
https://github.com/sdv-dev/RDT/blob/05b4036bddca04ab76967dc9d2de39317d2d7ab1/rdt/transformers/numerical.py#L131

In the `reverse_transform` stage, most of the time is consumed by:
https://github.com/sdv-dev/RDT/blob/05b4036bddca04ab76967dc9d2de39317d2d7ab1/rdt/transformers/numerical.py#L164

**Comment by fealho** [comment]
There are a few ways to improve the performance.

In the `fit` stage, `clean_data = data.dropna()` takes the most time, but it doesn't need to always be computed. Instead, it can be moved inside the `if self.rounding == 'auto':` loop, which doesn't run by default. This reduces the time consumed significantly, from

```
CPU times: user 3.04 ms, sys: 0 ns, total: 3.04 ms
Wall time: 3.25 ms
```

to 

```
CPU times: user 1.13 ms, sys: 0 ns, total: 1.13 ms
Wall time: 1.3 ms
```

**Comment by fealho** [comment]
Another change is to save the `pd.notnull(data)` value inside the `reverse_transform`, instead of computing it three times. This can be done by changing 
https://github.com/sdv-dev/RDT/blob/05b4036bddca04ab76967dc9d2de39317d2d7ab1/rdt/transformers/numerical.py#L158-L161

to 

```python3
not_null = pd.notnull(data)
if not_null.all():
    return data.round().astype(self._dtype)

data[not_null] = np.round(data[not_null]).astype(self._dtype)
```

However, this change does not seem to improve performance significantly.

**Comment by fealho** [comment]
To check the affect these changes have in performance, we run three datasets on the two models.
```
def make_dataset_1(size):
    # floats, no missing values
    x = np.random.normal(size=size)
    return x

def make_dataset_2(size, percent_to_set_to_nan=0.1):
    # floats, some missing values
    x = np.random.normal(size=size)
    x[np.random.choice(len(x), size=int(size*percent_to_set_to_nan))] = np.nan
    return x

def make_dataset_3(size):
    # ints, no missing values
    x = np.random.binomial(n=1000, p=0.1, size=size)
    return x
```
![image](https://user-images.githubusercontent.com/14266663/125661602-e91dc314-1672-434b-91a3-d2d39fc2379a.png)

As we can see, the `fit` performance improves significantly, while `transform` and `reverse_transform` stay relatively the same.

**Comment by csala** [comment]
> In the `fit` stage, `clean_data = data.dropna()` takes the most time, but it doesn't need to always be computed. Instead, it can be moved inside the `if self.rounding == 'auto':` loop, which doesn't run by default. This reduces the time consumed significantly, from

Good point! We should also be covering the rounding step, though. Could you also test it @fealho ?

Also, for that, maybe changing the `data.dropna()` to `data[pd.notnull(data)]` would make it faster (have not tried it)?

**Comment by fealho** [comment]
@csala the rounding step doesn't work if you keep NaNs, but we can move the logic inside with:

> roundable_data = data[~(np.isinf(data)|np.isnan(data))]

and make it a little bit faster.
