### ISSUE TITLE
Add performance-based testing

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/RDT#194]
We should add a way to test RDT transformers based on performance and resource usage by running the `profiling` function recently added and comparing the obtained results with some expected maximum time and memory usage.

The tests should be implemented as a single `test` module with a single test file that is parameterized with a collection of test cases found in configuration files written in JSON format.

Here would be the requirements of this:

1. The test file should be in the module:
`tests/performance/test_performance.py`.
2. The test cases should be inside a `tests/performance/test_cases` folder.
3. Test cases for each transformer can be put inside a folder dedicated to each one of them (e.g. `tests/performance/test_cases/NumericalTransformer/<some_test_case>.json`
4. The test function should be parametrized with the config files found inside the `test_cases` folder.
5. It should use the `profile_transformer` function on all the transformers and datasets defined by the config files

**Comment by csala** [comment]
This sounds good @amontanez24 
I updated a bit the description to add some more details and also match what you have already proposed in the corresponding PR.

**Comment by csala** [comment]
@amontanez24 Maybe we should also add a few more things to this:

1. Add a `Makefile` target (and `tasks.py` task) to run the performance tests alone
2. Modify the `invoke pytest` task to run unit and integration tests only
3. Add a specific check on the github workflow to run the performance tests on only one OS and python version, to prevent having multiple expected performances.
