### ISSUE TITLE
Audit GaussianCopulaTransformer

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/RDT#196]
Audit the time and memory performance of `transformers.GaussianCopulaTransformer`

https://github.com/sdv-dev/RDT/blob/d756679df61e6ab5330bf6132a1c155c2003f1ef/rdt/transformers/numerical.py#L167

**Comment by katxiao** [comment]
For the `fit` method, ~96% of the runtime is going to fitting all the models in the univariate candidates. 

https://github.com/sdv-dev/Copulas/blob/dfe3bb9cc035c8d4880724db69c86e749178e65b/copulas/univariate/selection.py#L25

In the univariate models, the majority of the runtime is going into the scipy model calls. For example,
https://github.com/sdv-dev/Copulas/blob/dfe3bb9cc035c8d4880724db69c86e749178e65b/copulas/univariate/beta.py#L28
and
https://github.com/sdv-dev/Copulas/blob/master/copulas/univariate/gamma.py#L25

**Comment by katxiao** [comment]
For the `transform` method, ~56% of the runtime goes into `super().transform`, and most of the remaining runtime (~43%) goes into computing the `_copula_transform`, which ends up calling the model's respective `cdf` methods [here](https://github.com/sdv-dev/Copulas/blob/dfe3bb9cc035c8d4880724db69c86e749178e65b/copulas/univariate/base.py#L535).

Similarly, for the `reverse_transform` method, ~60% of the runtime goes into calling `super().reverse_transform`, and ~40% of the runtime goes into calling `self._univariate.ppf` [here](https://github.com/sdv-dev/RDT/blob/master/rdt/transformers/numerical.py#L348), which ends up calling the respective scipy model's `ppf` methods [here](https://github.com/sdv-dev/Copulas/blob/dfe3bb9cc035c8d4880724db69c86e749178e65b/copulas/univariate/base.py#L554)

**Comment by katxiao** [comment]
When profiling against [this copulas branch ](https://github.com/sdv-dev/Copulas/tree/optimize-scipymodel-performance), I found that the runtime was about the same for `fit`, but noticed some speedups for `transform` and `reverse_transform` (shown below):

`transform`
Master:
```
CPU times: user 4.22 ms, sys: 0 ns, total: 4.22 ms
Wall time: 4.31 ms
```
Branch:
```
CPU times: user 2.27 ms, sys: 16 µs, total: 2.29 ms
Wall time: 2.3 ms
```

`reverse_transform`
Master:
```
CPU times: user 2.11 ms, sys: 6 µs, total: 2.12 ms
Wall time: 2.67 ms
```
Branch:
```
CPU times: user 440 µs, sys: 996 µs, total: 1.44 ms
Wall time: 1.82 ms
```

**Comment by csala** [comment]
> When profiling against [this copulas branch ](https://github.com/sdv-dev/Copulas/tree/optimize-scipymodel-performance), I found that the runtime was about the same for `fit`, but noticed some speedups for `transform` and `reverse_transform` (shown below)

The mentioned branch has been pre-released: https://pypi.org/project/copulas/0.5.1.dev0/

**Comment by csala** [comment]
The code will require no changes to solve this issue, since the newer Copulas version is within the supported range, so this can be closed already.
