### ISSUE TITLE
Update `pandas` dependency range

### ISSUE THREAD

**Issue by fealho** [sdv-dev/RDT#207]
`RDT` currently does not support `pandas>=1.1.5`, which does not include the newest versions.

We should investigate why blocks us from using the latest versions and adapt the code if necessary.

**Comment by npatki** [comment]
This has since been resolved. I can confirm the new version of RDT 1.0 is working with a higher pandas version; pip installed `1.3.5` by default.

Please reopen if there's still work to be done for this issue.
