### ISSUE TITLE
Improve unit test coverage

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/RDT#220]
### Problem Description

Improve unit test coverage by updating comments, fixing test order, and making tests more granular and robust.

### Expected behavior

In most of the unit test files, we can update the test comments to include a brief summary, the setup, inputs, and expected outputs. Most of the test files contain tests that have a single-line description or no description.

In `transformers/test_categorical.py` and `test_numerical.py` we can fix the ordering of the tests to match the ordering of the actual methods. 

`test_boolean.py`
- `test_fit` with nan values

`test_datetime.py`
The first two test here are end-to-end tests. We should re-write them to test individual methods.
- `test___init__`
- `test__transform` (no strip)
- `test__transform` (strip)
- `test_fit`
- `test_transform`

`test_categorical.py`
`TestCategoricalTransformer`
- `test__normalize`
- `test__get_category_from_start`

`TestLabelEncodingTransformer`
- `test_reverse_transform` (all values are already in map)

**Comment by npatki** [comment]
With the new RDT 1.0, we should have 100% unit test coverage that captures the above points. I'm closing off the issue but feel free to re-open if there are more items to be considered.

@amontanez24 FYI
