### ISSUE TITLE
Create ways for HyperTransformer to know which transformers to apply to each data type

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/RDT#232]
### Problem Description

Since RDT will be expanding the number of data types it supports, we will need a new way for the `HyperTransformer` to determine which transformers to apply to a specific data type. We propose the following additions:

1. A function, `get_transformers_by_type`, which iterates over all the existing Transformers and calls the `get_input_type` method to create a dictionary that indicates which transformers work with which data type.
2. A `DEFAULT_TRANSFORMERS` dict which may indicate what the default transformer for each data type is.
3. If a data type is not in the `DEFAULT_TRANSFORMERS` dictionary, the first transformer found is "the default".

**Comment by kveerama** [comment]
@amontanez24 in the above formulation, would this method in ```hypertransformer``` simply return a ```transformer``` which can process the ```input_type```  regardless whether or not that transformer ```output_type``` is ready for ML or not?
