### ISSUE TITLE
Enable users to specify transformers to use in HyperTransformer

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/RDT#233]
### Problem Description

The current `HyperTransformer` arguments could be expanded to also accept tuples of names instead of strings to indicate multiple fields that together represent a single data type. It also needs to be allow users to specify transformers for fields that are generated by other transformers.

### Expected behavior
The `HyperTransformer` should be able to take in the following parameters:

1. `field_types`: dictionary mapping single names or tuples of names to single data types
2. `data_type_transformers`: dictionary that maps from single data types to single transformers
3. `field_transformers`: Hierarchical way of specifying which transformer to apply to each field along all the process

**Initialization using no inputs:**
The simplest way to initialize a `HyperTransformer` is to use no inputs. If this is done, the `HyperTransformer` will infer which `transformers` to use for each column in the input data using the Pandas `dtype` of the column.

```python3
ht = HyperTransformer()
```
**Initialization using `field_types`:**
The `field_types` dictionary maps single columns or groups of columns, to their data type. This is especially useful if your data type does not easily map to a Pandas `dtype` or is more of a semantic type (ie. email). Defining these types for your fields will enable the `HyperTransformer` to select better transformers for them. If multiple columns are going to be an input for ONE data type, this can be specified by grouping the columns in a tuple.

In this example, your data has the columns: `company_email`, `home_phone`, `cell_phone`, `year_joined`, `month_joined` and `day_joined`.

```python3
ht = HyperTransformer(field_types={
    "company_email": "email",
    ("year", "month", "day"): "datetime",
    "home_phone": "phone_number",
    "cell_phone": "phone_number"
}
```

**Initialization using `data_type_transformers`:**
The `data_type_transformers` argument is useful if you want to use a specific `Transformer` or `Transformer` instance as the transformer for any field of a certain data type. Using this in conjunction with `field_types` allows a lot of control over `Transformer` specification.

In this example, we imagine there is a `AddressPrivateTransformer` that substitutes the street names in an address for privacy reasons.
```python3
ht = HyperTransformer(data_type_transformers={
    "categorical": CategoricalTransformer(fuzzy=True),
    "address": AddressPrivateTransformer,
    "ipv4": IPv4Transformer
})
```

**Initialization using `field_transformers`:**
The `field_transformers` are specified as a dictionary where the keys are the full name of the fields we want to transform and the values are the transformers. If a field is derived from another transformer, then its name is created by concatenating the field it came from to the output field name. Not all of the fields in your data, or their outputs need to be specified.

In this example, the data has a column named `email`.

```python3
ht = HyperTransformer(field_transformers={
    "email": EmailTransformer,
    "email.domain": EmailDomainTransformer,
    "email.username": CategoricalFuzzy,
    "email.domain.extension": OneHotEncoding,
})
```

**Comment by kveerama** [comment]
@amontanez24 in the above api does email.domain refer to the column created by transforming the column named email? And the subsequent are also following the same ?

**Comment by kveerama** [comment]
@amontanez24 upon re-reading, I think that is what it is doing. I am wondering if the goal is to apply a sequence of ```field_transformers``` then would it be easier for user to do something like this: 
```
HyperTransformer(field_name="email", field_transformers={EmailTransformer, EmailDomainTransformer, OneHotEncoding, CategoricalFuzzy})

```

Is there a reason, we want the user to specify the names for the intermediary columns?

**Comment by amontanez24** [comment]
@kveerama Yes, that is what it's doing. The problem with the list is that a `transformer` could have multiple outputs that go into different transformers, so that would need to be specified with a dictionary. I had a proposal for something like that but it became difficult to read as the number of layers increased. The user does not need to specify the `intermediary` columns, we're just trying to provide that flexibility.

**Comment by kveerama** [comment]
Interesting. So if I read your case above, 

-  ```EmailTransfomer``` outputs ```email.domain```, ```email.domain.extension```, ```email.username```
- ```EmailDomainTransformer``` transforms ```email.domain```
- ```OneHotEncoding``` transforms ```email.domain.extension```
-  ```CategoricalFuzzy``` transforms ```email.username```

**Comment by csala** [comment]
How does one know `EmailTransformer` is going to output `email.name` and `email.domain` columns?
