### ISSUE TITLE
Enable standalone usage of Transformers

### ISSUE THREAD

**Issue by csala** [sdv-dev/RDT#255]
After PR #224 the new-style transformers always expect a `pd.DataFrame` as input, alongside the name of the column or columns where it needs to be applied.

We should update the `BaseTransformer` to simplify the usage of standalone transformers and allow inputs such as:
- A `pandas.Series`: The column name can be inferred from the series name.
- A 1d `numpy.ndarray`: If the column name is not given, a `0` can be used.
- A 2d `numpy.ndarray`: If column names are given they should be indices of the table. If no column names are given, the indices of the entire table are used.

**Comment by npatki** [comment]
This feature request seems stale given our new RDT 1.0 release. While individual transformers can stand alone, the end-user interaction will be through a HyperTransformer.
