### ISSUE TITLE
OneHotEncodingTransformer return type is sometimes wrong

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/RDT#268]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* RDT version: v0.5.2
* Python version: 3.8
* Operating System: MacOS 11.6

### Error Description

`OneHotEncodingTransformer`'s `transform` method sometimes returns data of type `int`. However, the output type is `float`. It should be updated to always return output of type `float`.

### Steps to reproduce

Fit and transform the `OneHotEncodingTransformer` with input of all ints.

**Comment by npatki** [comment]
This issue is for an older version of RDTs and I cannot replicate it with RDT v1.0 and above. Please re-open if you still observe it.
