### ISSUE TITLE
`HyperTransformer` should crash if `field_transformers` doesn't correspond to an actual column

### ISSUE THREAD

**Issue by fealho** [sdv-dev/RDT#291]
When the `HyperTransformer` is initialized with `field_transformers` set to non-existing column names it behaves weirdly. We should force the `HyperTransformer` to crash if it's initialized incorrectly.

**Comment by npatki** [comment]
With the new RDT 1.0, the data passed into `fit` must exactly match the config. Seems like we can count this issue as resolved.

Please re-open if there's somethign more to be done.
