### ISSUE TITLE
`reverse_transform` should crash if a subset of the transformed columns are passed

### ISSUE THREAD

**Issue by fealho** [sdv-dev/RDT#294]
When the `HyperTransformer` transforms a column into multiple ones (e.g. `column_name.day`, `column_name.month`, `column_name.year`), the `reverse_transform` needs to take as input all the transformed columns. If only a subset is passed (e.g. only `column_name.day` and `column_name.year`) it should crash.

**Comment by npatki** [comment]
This is now resolved in the new RDT 1.0.

We've also added [new functions](https://docs.sdv.dev/rdt/usage/hypertransformer/transformation#transforming-a-subset-of-the-data) that are explicitly meant for transforming and reverse transforming subsets.
