### ISSUE TITLE
Improve RDT to be able to handle transformers with the same name

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/RDT#352]
### Problem Description

It is possible down the line the some RDTs will have the same name, since we are moving away from the `Transformer` suffix naming convention.

In the `__init__` file for the `transformers` module, the transformers are loaded into a dictionary that uses their names as the keys. The problem is that it doesn't use the full module + class name, so it is possible for there to be overlap. 
https://github.com/sdv-dev/RDT/blob/dbc550fc5e6cd62a032ab412aa8e2687bac82647/rdt/transformers/__init__.py#L45-L48

### Expected behavior

Methods that use the `TRANSFORMERS` dict should be able to load transformer classes that have the same name but belong to different modules

**Comment by npatki** [comment]
Seems like the PR that addressed this issue has already been merged. Closing this issue.

@fealho and @amontanez24 please re-open if the PR didn't fully address what's in here.
