### ISSUE TITLE
Update `BooleanTransformer` to make it user friendly

### ISSUE THREAD

**Issue by npatki** [sdv-dev/RDT#363]
### Problem Description

Let's update `BooleanTransformer` to make it more user friendly.

### Expected behavior

Name: `BinaryEncoder`

Functionality: 

- Missing value handling (see #362)
- Change `columns` (see #376 )
- Add `'mode'` as an option to replace missing values

```python
from transformers.boolean import BinaryEncoder

>>> be = BinaryEncoder(missing_value_replacement='mode')
>>> be = BinaryEncoder(missing_value_replacement=1, model_missing_values=True) 

>>> be.fit(data, column='user_is_active')
```

**Comment by amontanez24** [comment]
@npatki Quick question about adding `mode`, is this supposed to be the default?

**Comment by npatki** [comment]
@amontanez24 -- For all individual transformers, the default is to not replace any missing values
