### ISSUE TITLE
Move NullTransformer to be called from BaseTransformer

### ISSUE THREAD

**Issue by pvk-developer** [sdv-dev/RDT#387]
### Problem Description

Following on this thread https://github.com/sdv-dev/RDT/issues/362#issuecomment-1024751832 after a rework on the `NullTransformer` and the transformers themself, to share the same `API`, it makes sense to move the `NullTransformer` instantiation and usage to the `BaseTransformer` class, having in mind that there are transformers that do not need `NullTransformer` like the `CategoricalTransformer`, those should be able to work without having to fit a `NullTransformer`.

### Expected behavior

```python
class BaseTransformer:
    ...
    def fit(self, data, columns):
        ...
        self.null_transformer = NullTransformer(
            missing_value_replacement=self.missing_value_replacement, 
            model_missing_values = self.model_missing_values
        )
        self._fit(columns_data)
        self.null_transformer.fit(columns_data)
        
    def transform(self, data):
        ...
        transformed_data = self._transform(columns_data)
        return self.null_transformer.transform(transformed_data)
    
    def reverse_transform(self, data):
        ...
        columns_data = self.null_transformer.reverse_transform(columns_data)
        return self._reverse_transform(columns_data)
```

**Comment by amontanez24** [comment]
After discussing it seems tat this might more complicated than it's worth. Multiple transformers use the `NullTransformer` in an unorthodox way. For example, the `DatetimeTransformer`  applies a transformation on the fit, then trains the `Null_transformer` on that data. The `GaussianCopulaTransformer`  calls `super().fit_transform` which will remove all nans and replace with the mean. The it applies its own transformation afterwards.

To do this successfully would require altering each transformer to handle nulls on its own which may be more effort than the benefit of having moving the logic to the base. In other words, too many transformers would need to override that base functionality to make it worth it.
