### ISSUE TITLE
Update transformers by data type (in `HyperTransformer`)

### ISSUE THREAD

**Issue by npatki** [sdv-dev/RDT#403]
### Problem Description

The multi-level hierarchy of transformers might confuse users. Instead of exposing the complexity, let's allow a simple method to update all transformers by data type.

### Expected behavior

Instead of `update_default_data_type_transformers`, implement: `update_transformers_by_sdtype`.
- This updates all the transformers of the sdtype (no hierarchy exposed to the user) -- _note: under-the-hood, we can update the default as well as all the individual columns_
- This expects a param `sdtype` and a param `transformer`

```python
# assume ht is my HyperTransformer object
# update all categorical columns to OneHotEncoder
>>> ht.update_transformers_by_sdtype(
        sdtype='categorical',
        transformer=OneHotEncoder())

# all categorical transformers will update to OneHotEncoder now
# regardless of previous update history
```

### Edge Cases

**Scenario 1:** User tries to use this method without first using `detect_initial_config` (see https://github.com/sdv-dev/RDT/issues/399 )

```python
>>> ht = HyperTransformer()
>>> ht.update_transformers_by_sdtype(sdtype='categorical', transformer=OneHotEncoder())
Error: Nothing to update. Use the `detect_initial_config` method to pre-populate all the sdtypes
and transformers from your dataset.
```

**Scenario 2:** User tries to use this method after calling `fit` or `fit_transform` on the data already.
```python
>>> ht.update_transformers_by_sdtype(sdtype='categorical', transformer=OneHotEncoder())
Warning: For this change to take effect, please refit your data using 'fit' or 'fit_transform'.
```

**Comment by amontanez24** [comment]
We meant to change the name to `update_sdtypes` right?
