### ISSUE TITLE
Create methods for getting and setting a config

### ISSUE THREAD

**Issue by npatki** [sdv-dev/RDT#418]
### Problem Description

The HyperTransformer's behavior is determined by the `sdtypes` and `transformers` -- called the config. Provide methods to get and set these.

### Expected behavior

Implement a `get_config()` method that returns the `sdtypes` and `transformers` for each of the column names.

```python
{
  'sdtypes': {
    'colA': 'datetime',
    'colB': 'categorical'
  },
  'transformers': {
    'colA': <UnixTimestampEncoder(missing_value_replacement="mean")>,
    'colB': <FrequencyEncoder()>
  }
}
```

Implement a `set_config()` method that accepts a param (`config`) where the user can specify this themselves. Note that this method resets the entire config. If a user wishes to modify parts of it, they must use the `update_sdtypes` or `update_transformers` methods instead.

```python
ht.set_config(config={
  'sdtypes': {
    'colA': 'datetime',
    'colB': 'categorical'
  },
  'transformers': {
    'colA': UnixTimestampEncoder(missing_value_replacement="mean"),
    'colB': FrequencyEncoder()
  }
})
```

While we're at it, we can also remove any existing getters for either the sdtypes or transformers alone.

### Edge Cases

A user may be attempting to set a transformer that is incompatible with a particular sdtype. Throw a warning for each incompatible column.

```python
ht.set_config(config={
  'sdtypes': {
    'last_login': 'datetime'
  },
  'transformers': {
    'last_login': FloatFormatter(missing_value_replacement="mean")
  }
})
Warning: You are assigning a numerical transformer to a datetime column ('last_login').
If the transformer doesn't match the sdtype, it may lead to errors.
```

**Comment by amontanez24** [comment]
Should `get_config` just print the configuration or return it?

**Comment by npatki** [comment]
Ah it should return it to align with other `get` methods. I'll update the issue.
