### ISSUE TITLE
Poor error message for missing columns

### ISSUE THREAD

**Issue by fealho** [sdv-dev/RDT#498]
When attempting to transform a subset of the original data, the error message prints:

`There are unexpected columns in the data you are trying to transform. You must provide a transformed dataset with all the columns from the original data.`.

This is misleading, since there are no unexpected columns, only missing columns.

**Comment by npatki** [comment]
We updated the error message to:

`The data you are trying to transform has different columns than the original data. Column names and their sdtypes must be the same. Use the method 'get_config()' to see the expected values.`

To cover both cases of strict subset and non-strict subsets.
