### ISSUE TITLE
Inconsistency in date format after reverse transform

### ISSUE THREAD

**Issue by sarahmish** [sdv-dev/RDT#515]
### Environment details

If you are already running RDT, please indicate the following details about the environment in
which you are running it:

* RDT version: 1.0.0
* Python version: 3.7
* Operating System: google colab

### Problem description

For date columns, after transforming it and then reversing the transform, if the entry that used to be null is filled, the formatting is off and contains time. It’s probably the average time in consideration to all the other values 24 / 4 = 6. In the scenario where the third row is reversed into NaT, we don’t see this issue. See screen shots below

**Expected format**
In this case, row 3 (the original one with NaT value) is reversed to NaT so we don't see the problem.
<img width="575" alt="Screen Shot 2022-05-16 at 6 13 11 PM" src="https://user-images.githubusercontent.com/40212131/168690983-2d7a6f01-454e-4184-b6c5-8ea5114deb90.png">

**Inconsistent format**
In this case, row 3 is reversed to an average value so we see inconsistency with the output where time is now part of the format.
<img width="666" alt="Screen Shot 2022-05-16 at 6 12 18 PM" src="https://user-images.githubusercontent.com/40212131/168690873-fa4c912e-42de-4510-8b72-dc6daf95ca4e.png">

### Reproducing the problem
Link to colab notebook ([link](https://colab.research.google.com/drive/1BZ2wgMFYSwUwPxMQhS7GahWlR5xZJpcs?usp=sharing))

```python3
from rdt import get_demo, HyperTransformer

data = get_demo()

ht = HyperTransformer()
ht.detect_initial_config(data=data)

transformed_data = ht.fit_transform(data)
ht.reverse_transform(transformed_data)
```

`HyperTransformer` config
```
Detecting a new config from the data ... SUCCESS
Setting the new config ... SUCCESS
Config:
{
    "sdtypes": {
        "last_login": "datetime",
        "email_optin": "boolean",
        "credit_card": "categorical",
        "age": "numerical",
        "dollars_spent": "numerical"
    },
    "transformers": {
        "last_login": UnixTimestampEncoder(missing_value_replacement='mean'),
        "email_optin": BinaryEncoder(missing_value_replacement='mode'),
        "credit_card": FrequencyEncoder(),
        "age": FloatFormatter(missing_value_replacement='mean'),
        "dollars_spent": FloatFormatter(missing_value_replacement='mean')
    }
}
```

**Comment by npatki** [comment]
Thanks for filing. I can replicate this and it appears to be a bug in the way we reverse transform only when `missing_value_replacement='mean'` and `model_missing_values=False`.

It works on all other combinations:

- If `model_missing_values=True` and
- If `missing_value_replacement' is `'mode'` or `'None'`
