### ISSUE TITLE
Update `FloatFormatter` with parameters for the computer representation

### ISSUE THREAD

**Issue by npatki** [sdv-dev/RDT#521]
### Problem Description

As a user, I want to make sure the min/max values in the reverse transform can be represented by the machine.

### Expected behavior

Add the following parameter to `FloatFormatter`:
- `computer_type`: Default (`'Float'`). Accepts: `'Int8'`, `'Int16'`, `'Int32'`, `'Int64'`, `'UInt8'`, `'UInt16'`, `'UInt32'`, `'UInt64'`, `'Float'`

**Functionality Changes**:
- During `fit`, store the original `dtype` of the column
- During the `transform`, convert everything to `Float` for machine learning purposes.
- During the `reverse_transform`:Cast back to the original dtype. As an extra measure: Clip the values to the min and max machine limits for the given `computer_representation`, and round back to whole numbers if needed. (This is a no-op for `Float`.) Note if: `learn_min_max_bounds=True`, then use the learned values instead.

_Note: The `dtype` may be different than the computer representation. For example, pandas might have read in a column as `Int64` by default but the user might be telling us it's supposed to be `UInt8`. Always defer to the parameter, not the dtype._

**Errors**
During `fit` or `transform`: Throw an error if the data is out of bounds according to the computer representation. _Note: It does not matter what the actual pandas dtype is, only what the computer representation parameter is._
```python
# limits correspond to uint8
transformer = FloatFormatter(computer_representation='UInt8')
transformer.fit(data, column='test')
Error: The minimum value in column 'test' is -5. All values represented by 'UInt8' must be in the range [0, 255].

transformer.transform(data)
Error: The minimum value in column 'test' is -5. All values represented by 'UInt8' must be in the range [0, 255].
```

### Additional context

- Info about pandas dtypes [here](https://pbpython.com/pandas_dtypes.html) and [here](https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes)
- A reference for standard min/max values: [here](https://crystal-lang.org/reference/1.4/syntax_and_semantics/literals/integers.html#integers)

See #518 as an example for where this fails today.

**Comment by fealho** [comment]
@npatki @amontanez24 Should we also validate whether the data type is correct? E.g. if the data contains floats but `computer_representation` is given as an integer, should we raise an error?

**Comment by npatki** [comment]
@fealho Right the main things to check for would be if the user-specified value cannot possibly be correct. We would do this in the `fit` or `transform`.

There are only 2 cases I can think of:

1. Eg. if the user said something is an `Int8`, all values should be between 0 and 255. Same for all other `Int` types.
2. If the user has specified something is an `Int`, there can be no fractions. Eg. it's ok for a value of `2.000` but it is not ok to have a value of `2.5`.

I think we are already doing (1) and I am in favor of adding (2).
