### ISSUE TITLE
Unable to use HyperTransformer functions

### ISSUE THREAD

**Issue by dominusoctane** [sdv-dev/RDT#530]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* RDT version: v1.1.0 - 2022-6-9 [Latest](https://github.com/sdv-dev/RDT/releases/latest)
* Python version: Python 3.6.9
* Operating System: CentOs Linux Version 7 (Core)

### Error Description

I'm trying to get the demo run working for the RDT library. However, I am unable to get this to work.
I get this error:
<img width="980" alt="Screen Shot 2022-08-02 at 13 17 06" src="https://user-images.githubusercontent.com/61175343/182445463-59ccbd0f-cee9-4f94-9580-281b7e21a742.png">

### Steps to reproduce
Follow the QuickStart:

from rdt import HyperTransformer
from rdt import get_demo

customers = get_demo()
ht=HyperTransformer()
ht.detect_initial_config(data=customers)

**Comment by npatki** [comment]
Hi @dominusoctane, thanks for the detailed bug report. Unfortunately, I am unable to replicate it.

I've seen this exact error appear when there has accidentally been an older version installed. Some users have reported issues around iPython notebooks caching older packages. Would you mind double-checking the `rdt` library version?

```python
import rdt

print(rdt.__version__)
```

**Comment by npatki** [comment]
Hi @dominusoctane, I'm closing this issue off as unable to replicate.

If you are continuing to experience this even with the latest version, please reply to the issue and I'll re-open it to investigate.
