### ISSUE TITLE
Remove '.value' suffix

### ISSUE THREAD

**Issue by amontanez24** [sdv-dev/RDT#533]
### Problem Description

As a user, it is extra work to figure out which output column directly maps to the original since the name is modified. In cases where the transformation creates a new column or completely changes the input column, this makes sense, but in cases like the `FloatFormatter`, it would be nice if the formatted column kept the same name.

### Expected behavior

- Get rid of the `'.value'` suffix on output column names

### Additional context

- we can probably modify the `OUTPUT_SDTYPES` attribute everywhere to accept None or an empty string and then modify the following lines to not add a `.`:
https://github.com/sdv-dev/RDT/blob/2c9e53627bd9c626ee937fb770624b8432a41e9e/rdt/transformers/base.py#L65-L73
- There are a few methods that depend on the `.value` suffix because they use the `_transformer_tree`. After #557 , we can remove all of these methods and the `_transformer_tree` completely.

**Comment by npatki** [comment]
Note that other suffixes such as `.null` or `.component` can remain.

The `.value` applies to the following transformers:
- `BinaryEncoder`
- `FrequencyEncoder`, `LabelEncoder`, `CustomLabelEncoder`
- `OptimizedTimestampEncoder`, `TimestampEncoder`
- `FloatFormatter`, `GaussianNormalizer`
