### ISSUE TITLE
Allowing for scipy>=1.8?

### ISSUE THREAD

**Issue by AndresAlgaba** [sdv-dev/RDT#570]
### Problem Description
The restriction of scipy<1.8 is causing problems on some of my projects with the Mac M1. 

### Expected behavior
I wondered whether the restriction could be set to something like scipy<2. Or are there any good reasons for the fix on <1.8? 

### Additional context
The original issue at scipy:
https://github.com/scipy/scipy/issues/13409

Which seems to be solved from 1.8 onwards:
https://github.com/scipy/scipy/pull/14151

Backward incompatible changes for 1.8 and 1.9:
- https://docs.scipy.org/doc/scipy/release.1.8.0.html#backwards-incompatible-changes
- https://docs.scipy.org/doc/scipy/release.1.9.0.html#backwards-incompatible-changes

It seems that <=1.8 will do, but maybe <2 is preferred and more in line with the other restrictions. For example, in the SDMetrics and SDGym packages: https://github.com/sdv-dev/SDMetrics/blob/master/setup.py and https://github.com/sdv-dev/SDGym/blob/master/setup.py

**Comment by AndresAlgaba** [comment]
Backward incompatible changes for 1.8 and 1.9:

- https://docs.scipy.org/doc/scipy/release.1.8.0.html#backwards-incompatible-changes
- https://docs.scipy.org/doc/scipy/release.1.9.0.html#backwards-incompatible-changes

**Comment by npatki** [comment]
It seems like this issue has since been resolved, as I'm seeing the max cap of `scipy` is now `2` in our [setup requirements](https://github.com/sdv-dev/RDT/blob/master/setup.py).

```
    "scipy>=1.5.4,<2;python_version<'3.10'",
    "scipy>=1.9.2,<2;python_version>='3.10'",
```
