### ISSUE TITLE
`ClusterBasedNormalizer` missing in the Python 3.10 wheel

### ISSUE THREAD

**Issue by bcebere** [sdv-dev/RDT#590]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* RDT version: 0.2.1(?)
* Python version: 3.10
* Operating System: Ubuntu

### Error Description

Installing RDT from PyPI for Python 3.10 uses version `0.2.1`, which doesn't support ClusterBasedNormalizer.

### Steps to reproduce

```
conda create -n py310 python=3.10
pip install rdt
python -c "from rdt.transfomers import ClusterBasedNormalizer"
```

**Comment by npatki** [comment]
Hi @bcebere, thanks for filing! The RDT library doesn't currently support Python 3.10  (see [installation requirements](https://docs.sdv.dev/rdt/getting-started/installation#requirements)).

I've filed #593 for supporting newer versions of Python and suggest we use that issue to track the change. When we make the upgrade, we'll make sure all transformers are suported.

**Comment by bcebere** [comment]
Thank you for the reply.

It is a bit misleading that in a Python 3.10 env I get `rdt` version 0.2.1. `rdt-0.2.1-py2.py3-none-any.whl` , which is from Jan 17, 2020.

Not sure how this gets downloaded, since the newer versions do not support Python 3.10.

**Comment by npatki** [comment]
@bcebere, no problem. I agree that's misleading and I see what's happening now: this [very old version](https://pypi.org/project/rdt/0.2.1/) of RDT has just specified that Python must be `>=3.5` with no upper limit. Therefore, the `pip` resolver is determining that it's compatible with Python 3.10. 

Unfortunately, it doesn't seem to be something we can retroactively resolve that easily. But do know that we are actively working on Python 3.10 for the next release, so you'll be able to install the latest version `1.3.0` when it comes out!

**Comment by npatki** [comment]
I think we may have actually had similar issues in the past. I've filed #595 as a central place to track it.

**Comment by npatki** [comment]
Hello, we added Python 3.10 support for the RDT library in v1.3.0 (see [release notes](https://github.com/sdv-dev/RDT/releases/tag/v1.3.0)), so I'm closing off the issue as resolved.

(There is still the issue that `0.2.1` gets installed for new Python versions, which we'll use #595 to track.)
