### ISSUE TITLE
Consider deprecating the `FrequencyEncoder`

### ISSUE THREAD

**Issue by npatki** [sdv-dev/RDT#614]
### Problem Description
The `FrequencyEncoder` takes up more time than `LabelEncoder`. Furthermore, we have evidence that `LabelEncoder` produces data that is better quality for data science purposes.

Considering this, there is not much benefit to keeping `FrequencyEncoder` around in our library. 

### Expected behavior
Issue a `FutureWarning` whenever a `FrequencyEncoder` object is being created. 

```
The 'FrequencyEncoder' transformer will no longer be supported in future versions of the RDT library.
Please use the 'UniformEncoder' transformer instead.
```

Additionally, we should **apply the UniformEncoder** as a default for categorical columns in the `detect_initial_config` method.

**Comment by rwedge** [comment]
@npatki is the `LabelEncoder` suggestion in the warning message out of date?

**Comment by npatki** [comment]
@rwedge Yes, updated issue.
