### ISSUE TITLE
detect_initial_config() return attribute error

### ISSUE THREAD

**Issue by bearberror** [sdv-dev/RDT#625]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* RDT version: 1.3.0
* Python version: 3.9
* Operating System: MacOS ARM

### Error Description
Found this error when call HyperTransformer().detect_initail_config(DataFrame)

AttributeError                            Traceback (most recent call last)
/var/folders/2l/lfnt8r350xz54773zh760tqh0000gn/T/ipykernel_22733/2451760243.py in <module>
      1 ht = HyperTransformer()
----> 2 ht.detect_initial_config(data)

/opt/anaconda3/lib/python3.9/site-packages/rdt/hyper_transformer.py in detect_initial_config(self, data)
    515         # Set the sdtypes and transformers of all fields to their defaults
    516         LOGGER.info('Detecting a new config from the data ... SUCCESS')
--> 517         self._learn_config(data)
    518 
    519         LOGGER.info('Setting the new config ... SUCCESS')

/opt/anaconda3/lib/python3.9/site-packages/rdt/hyper_transformer.py in _learn_config(self, data)
    487         for field in data:
    488             if field not in self.field_sdtypes:
--> 489                 self._set_field_sdtype(data, field)
    490             if field not in self.field_transformers:
    491                 sdtype = self.field_sdtypes[field]

/opt/anaconda3/lib/python3.9/site-packages/rdt/hyper_transformer.py in _set_field_sdtype(self, data, field)
    472     def _set_field_sdtype(self, data, field):
    473         clean_data = data[field].dropna()
--> 474         kind = clean_data.infer_objects().dtype.kind
    475         self.field_sdtypes[field] = self._DTYPES_TO_SDTYPES[kind]
...
-> 5902         return object.__getattribute__(self, name)
   5903 
   5904     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'dtype'

**Comment by npatki** [comment]
Hi @bearberror, thanks for providing all the details.

The error may be indicating an issue with the `DataFrame` object that you are inputting into `detect_initial_config`. Would you be able to provide more details about what this object is and how you are creating it?

It would also be good to verify that your `DataFrame` is a [pandas.DataFrame object](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html):

```python
print(type(DataFrame))
```
should print out
```
<class 'pandas.core.frame.DataFrame'>
```

**Comment by npatki** [comment]
Hi @bearberror, I'm closing this issue since it's been inactive for some time. 

If you're still encountering this problem, feel free to reply and I can reopen the issue to investigate!
