### ISSUE TITLE
How to obtain the middle statistics or category-value mapping

### ISSUE THREAD

**Issue by taokz** [sdv-dev/RDT#667]
#### Environment details

* RDT version: 1.5.0.dev1
* Python version: python 3.10

#### Problem description

I am curious about how to extract the intermediate values, for example, there should be a mapping dictionary of category-value pairs  or statistics for reverse_transform. However, it seems the document did not provide the corresponding interface. Could you provide some hints to obtain them?

**Comment by pvk-developer** [comment]
Hi @taokz nice to meet you! We have different strategies for the transformers, some of them have `intervals` and some have `categories_to_values` and `values_to_categories` to reverse transform.

#### Frequency Encoder
The frequency encoder works with intervals and while fitting those are being created and you can access them by running `transformer.intervals`. Here is a short example:
```python
import pandas as pd
from rdt.transformers import FrequencyEncoder

data = pd.DataFrame({'categories': ['a', 'b', 'c']})
fe_transformer = FrequencyEncoder()
fe_transformer.fit(data, 'categories')
fe_transformer.intervals
Out: 
{'a': (0, 0.3333333333333333, 0.16666666666666666, 0.05555555555555555),
 'b': (0.3333333333333333, 0.6666666666666666, 0.5, 0.05555555555555555),
 'c': (0.6666666666666666, 1.0, 0.8333333333333333, 0.05555555555555555)}

```
Intervals is a dictionary containing the `category` as a key and then a tuple with starting value, ending value, mean value and std. When reverse transform occurs we check if the value is between those and assign the corresponding value. This values are clipped to `1`, so no matter how many categories you have the start will be 0 and end on the last category will be 1 (or close to 1).

#### Label Encoder
On the other hand, label encoder works directly with mapping, where you have `values_to_categories` and `categories_to_values` attributes that will give you such dictionary mappings. Here is a short example:

```python
import pandas as pd
from rdt.transformers import LabelEncoder

data = pd.DataFrame({'categories': ['a', 'b', 'c']})
le_transformer = LabelEncoder()
le_transformer.fit(data, 'categories')
le_transformer.values_to_categories
Out:
{0: 'a', 1: 'b', 2: 'c'}

le_transformer.categories_to_values
Out:
{'a': 0, 'b': 1, 'c': 2}
```

**Comment by taokz** [comment]
@pvk-developer thank you for your detailed explanation!
