### ISSUE TITLE
AttributeError: 'GaussianNormalizer' object has no attribute 'distribution'

### ISSUE THREAD

**Issue by kirillzx** [sdv-dev/RDT#869]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* RDT version: 1.12.3
* Python version: 3.11.4
* Operating System: MacOS Sonoma

### Error Description

I have the following error when I try to append the normalizer to a list or try to print it: "AttributeError: 'GaussianNormalizer' object has no attribute 'distribution'"

For example:
array = []
transform = GaussianNormalizer(learn_rounding_scheme=True, enforce_min_max_values=True)
array.append(transform)

or 

print(transform)

**Comment by srinify** [comment]
Thanks for raising this @kirillzx I've opened a new bug report with instructions for the team to replicate and fix. Let's track the progress of the issue over there! 

https://github.com/sdv-dev/RDT/issues/883
